### ISSUE TITLE
[core Gramine] Update docs of Gramine with link to this repo

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine-scaffolding#8]
After we merge everything here, and this repo will be finalized, we should update the core Gramine documentation: https://github.com/gramineproject/gramine/blob/master/Documentation/scag-installation.rst

We'll need to at least update the links to this new repo.

**Comment by woju** [comment]
@dimakuv @oshogbo Is this done in gramineproject/gramine#1838?

**Comment by dimakuv** [comment]
Yes from my side. Let's see if @oshogbo had something additional in mind.

**Comment by oshogbo** [comment]
Yes. It's done.
